name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3

    - name: Build
      run: msbuild PlantsVsZombies.sln

    - name: Upload Artifact
      uses: actions/upload-artifact@main
      with:
        name: PvZ-QotL-Build
        path: |
          Debug/

  upload:
    name: Upload artifacts
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: probonopd/uploadtool

    - uses: actions/download-artifact@main
      with:
       name: PvZ-QotL-Build
       path: Debug

    - name: Debug step
      run: |
        find . -type f

    - name: Upload Continuous Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        UPLOAD_KEY: ${{ secrets.UPLOAD_KEY }}
      run: |
        ./upload.sh \
          PvZ-QotL-Build/PvZ-QotL-Build.zip
          
